# checklist

<!-- badges: start -->
<!-- badges: end -->

Inspired by projects like [`{goodpractice}`](https://github.com/MangoTheCat/goodpractice) and [`{checkers}`](https://github.com/ropenscilabs/checkers), this package implements a semi-automated checklist for scripts and program files.  

Its ostensible primary purpose is to help people in my programming classes write better
code (i.e., come to grips with me being uptight and obsessive-compulsive about spaces and indentation).  
It's actual primary purpose is to save me from having to write out repetitive nagging comments about sloppy homework.

## Installation

``` r
remotes::install_github("fabian-s/checklist")
```

## Example


`{checklist}` only has one function, called `checklist`.  
The input for `checklist` is the path to a single R script file or a folder containing R scripts. 
`checklist` then runs a lot of different checks for proper formatting and sensible coding style on these. 
It is fairly likely to produce a lot of false positives, so use your judgment. 

```{r}
checklist::checklist(
  system.file("examples", package = "checklist")
)
```

